server:
  port: 8081
  tomcat:
    accept-count: 200
    max-connections: 2000
    threads:
      max: 160
      min-spare: 20
  servlet:
    context-path: /api

#spring:
#  security:
#    user:
#      name: admin
#      password: admin

rocksdb:
  path: /item

debug: false
logging:
  config: classpath:logback.xml