// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course.proto

package com.flx.protobuf.dto;

public interface courseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:course)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint64 score = 2;</code>
   * @return The score.
   */
  long getScore();
}
